version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    command: postgres -c max_connections=200
    environment:
      PGUSER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  
  payment:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8090"
    depends_on: [postgres]
    command: -env docker