// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repos

import (
	"time"

	"github.com/google/uuid"
)

// Storing merchant data
type Merchant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreateAt  time.Time `json:"create_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Storing transactions data
type Tx struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
	Amount     float64   `json:"amount"`
	TxType     int64     `json:"tx_type"`
	CreateAt   time.Time `json:"create_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
