// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repos

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (Tx, error)
	GetUser(ctx context.Context, email string) (GetUserRow, error)
	ListTransactions(ctx context.Context) ([]Tx, error)
	ListTransactionsByMechant(ctx context.Context, merchantID uuid.UUID) ([]Tx, error)
	ListUsers(ctx context.Context) ([]Merchant, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error
	UpdateTransactionType(ctx context.Context, arg UpdateTransactionTypeParams) (UpdateTransactionTypeRow, error)
}

var _ Querier = (*Queries)(nil)
